CRM.Web/Areas/Admin/Controllers/LoginController.cs
using CRM.IServices;
using CRM.Model.ModelViews;
using CRM.WebHelper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CRM.Web.Areas.Admin.Controllers
{
    public class LoginController : BaseController
    {
        public LoginController(IsysUserInfoServices isysUserInfoService, IsysFunctionServices isysFunctionServices)
        {
            base.isysUserInfoServices = isysUserInfoService ?? throw new ArgumentNullException(nameof(IsysUserInfoServices));
            base.isysFunctionServices = isysFunctionServices ?? throw new ArgumentNullException(nameof(IsysFunctionServices));
        }

        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(LoginInfo model)
        {
            return View();
        }
    }
}

CRM.Web/Areas/Admin/Controllers/VCodeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Drawing;
using CRM.Common;
using System.IO;
using System.Drawing.Imaging;

namespace CRM.Web.Areas.Admin.Controllers
{
    public class VCodeController : Controller
    {
        // GET: Admin/VCode
        public ActionResult Index()
        {
            var code = GetHashCode(1);
            Session[Keys.code] = code;
            using (Image img = new Bitmap(75, 30))
            {
                using (Graphics g = Graphics.FromImage(img))
                {
                    g.Clear(Color.White);
                    g.DrawString(code, new Font("黑体", 14, FontStyle.Bold | FontStyle.Italic | FontStyle.Strikeout),new SolidBrush(Color.Red),1,2);
                }

                byte[] imgBuffer;
                using (MemoryStream ms = new MemoryStream())
                {
                    img.Save(ms, ImageFormat.Jpeg);
                    imgBuffer = ms.ToArray();
                }

                return File(imgBuffer,"image/jpeg");
            }
        }

        private string GetHashCode(int v)
        {
            Random r = new Random();
            string str = "123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ";
            string res = string.Empty;
            int leng = str.Length;
            for (int j = 0; j < 4; j++)
            {
                for (int i = 0; i < v; i++)
                {
                    res += str[r.Next(leng)];
                }
            }
            return res;
        }
    }
}

CRM.Web/Controllers/HomeController.cs
using CRM.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using CRM.IServices;
namespace CRM.Web.Controllers
{
    public class HomeController : Controller
    {

   
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public async Task<ActionResult> Contact()
        {
            ViewBag.Message = "Your contact page.";
            await Task.CompletedTask;
            return View();
        }
    }
}

CRM.Web/Areas/Admin/Views/Login/Login.cshtml
@model CRM.Model.ModelViews.LoginInfo

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Login</title>

    <link href="~/Content/bootstrap.all.css" rel="stylesheet" />
    <style type="text/css">

        .login-title {
            text-align: right;
            padding-right: 3px;
        }

        img {
            margin-right: 5px;
            cursor:pointer;
        }

        .error {
            color: red;
        }
    </style>
</head>
<body>
    <div class="modal" id="staticBackdrop" data-backdrop="static" data-keyboard="false" tabindex="-1" role="dialog" aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="staticBackdropLabel">欢迎登录CRM管理系统</h5>
                    @*<button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>*@
                </div>
                <div class="modal-body">
                    @using (Ajax.BeginForm("Login", "Login", new AjaxOptions()
                    {
                        Url = Url.Action("Login", "Login"),
                        HttpMethod = "Post",
                        OnBegin = "begin",
                        OnSuccess = "success"
                    },new { id="frmLogin"}))
                    {
                        <div class="list">
                            <div class="form-group">
                                <label class="login-title">@Html.DisplayNameFor(c => c.uLoginName)</label>
                                @Html.TextBoxFor(c => c.uLoginName, new { @class = "form-control", maxLength = 15 })
                                <small id="uLoginName" class="form-text text-muted">@Html.ValidationMessageFor(c => c.uLoginName, "", new { @class = "error" })</small>
                            </div>
                            <div class="form-group">
                                <label class="login-title">@Html.DisplayNameFor(c => c.uLoginPWD)</label>
                                @Html.PasswordFor(c => c.uLoginPWD, new { @class = "form-control", maxLength = 15 })
                                <small id="uLoginPWD" class="form-text text-muted">@Html.ValidationMessageFor(c => c.uLoginPWD, "", new { @class = "error" })</small>
                            </div>
                            <div class="form-group">
                                <label class="login-title">@Html.DisplayNameFor(c => c.VCode)</label>
                                <div><img onclick="refreshCode()" class="rounded float-left" src="@Url.Action("Index","VCode")" id="imgCode" style="height: calc(1.5em + .75rem + 2px);" width="65" /></div>
                                @Html.TextBoxFor(c => c.VCode, new { @class = "form-control", style = "width:60px;", maxLength = 4 })
                                <small id="VCode" class="form-text text-muted">@Html.ValidationMessageFor(c => c.VCode, "", new { @class = "error" })</small>
                            </div>
                            <div style="margin-top:20px">
                                <input type="submit" value="登录" class="btn btn-primary"/>
                                <input type="reset" value="重置" class="btn btn-secondary"/>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script type="text/javascript">
        $(function () {
            $("#staticBackdrop").modal('show');
        });

        let refreshCode = () => {
            $("#imgCode").attr("src", '@Url.Action("Index","VCode")' + '?timespan=' + Math.random());//(new Date()).valueOf());
        }

    </script>
</body>
</html>

CRM.Web/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

CRM.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

CRM.Web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

CRM.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

CRM.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 我的 ASP.NET 应用程序</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("应用程序名称", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("主页", "Index", "Home")</li>
                    <li>@Html.ActionLink("关于", "About", "Home")</li>
                    <li>@Html.ActionLink("联系方式", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - 我的 ASP.NET 应用程序</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>